apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: date-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: date
        spec:
          containers:
          - name: alpine
            image: alpine
            command: ["/bin/sh", "-c", "date"]
          restartPolicy: OnFailure