version: '3'
services:
  main:
    build:
        context: .
        args:
            - http_proxy
            - https_proxy
            - no_proxy
    image: training/custom_layers
#    volumes:
#      - ./data:/tmp/c
